// app/components/app/ChatBubble.vue
<script setup lang="ts">
import showndown from "showdown";

const converter = new showndown.Converter({
	simplifiedAutoLink: true,
	strikethrough: true,
	tables: true,
	tasklists: true,
	emoji: true,
	simpleLineBreaks: true,
});

defineProps<{
	side: "left" | "right";
	name: string;
	message: string;
	hour: string;
	extraData?: {
		pdf: string;
		data: Record<string, any>;
	}[];
	loading?: boolean;
	files?: Array<{ name: string; data: string }>;
}>();

function getColumnsFromExtraData(pdfData: Record<string, any>) {
	if (!pdfData) return [];
	return Object.keys(pdfData).map((key) => ({
		field: key,
		header: key,
	}));
}

function parseTitle(title: string) {
	const convert = {
		coes: "ções",
		encias: "ências",
	};

	let replaced = title.replace(/([A-Z])/g, " $1").replace(/^./, (str) => str.toUpperCase());

	for (const key in convert) {
		if (replaced.includes(key)) replaced = replaced.replace(key, (convert as any)[key]);
	}

	return replaced;
}
</script>

<template>
	<div>
		<div :class="`chat ${side === 'left' ? 'chat-start' : 'chat-end'}`">
			<div class="flex text-center place-items-center chat-image avatar">
				<Avatar v-if="side === 'left'" image="images/cloudia.png" size="large" shape="circle" />
				<Avatar v-else size="large" shape="circle" style="display: flex !important">
					<template #icon>
						<Icon name="fa6-solid:user" />
					</template>
				</Avatar>
			</div>
			<div v-if="!loading" class="chat-header">
				{{ name }}
				<time class="text-xs opacity-50">{{ hour }}</time>
			</div>
			<div v-else class="chat-bubble">
				<Icon name="eos-icons:three-dots-loading" size="24" />
			</div>
			<!-- <div v-if="!loading" class="chat-bubble">{{ message }}</div> -->
			<span v-if="!loading" class="chat-bubble" v-html="converter.makeHtml(message)"></span>

			<div v-if="files" class="flex flex-wrap gap-2">
				<div v-for="(file, i) of files" :key="i" class="flex items-center gap-2 m-2 rounded-lg">
					<Icon name="fa6-solid:file" />
					<span>{{ file.name }}</span>
				</div>
			</div>
		</div>
		<div v-for="pdf of extraData" :key="pdf.pdf" class="flex flex-col gap-5 mt-2">
			<h2>Detalhes do arquivo: {{ pdf.pdf }}</h2>

			<Card v-for="(column, i) of getColumnsFromExtraData(pdf.data)" :key="i" class="card-slate">
				<template #title>{{ parseTitle(column.header) }}</template>
				<template #content>
					<p class="p-2 m-0 rounded-sm">
						<span v-if="!pdf.data[column.field]">Sem dados</span>
						<RenderArray v-else-if="Array.isArray(pdf.data[column.field])" :lista="pdf.data[column.field]" />
						<RenderObject v-else-if="typeof pdf.data[column.field] === 'object'" :objeto="pdf.data[column.field]" />
						<span v-else>{{ pdf.data[column.field] }}</span>
					</p>
				</template>
			</Card>
			<!-- <Column v-for="(column, i) of getColumnsFromExtraData(pdf.data)" :key="i" :field="column.field" :header="column.header"></Column> -->
		</div>
	</div>
</template>

<style lang="scss">
.card-slate > .p-card-body {
	background-color: rgb(226 232 240);
}
</style>

// mobile/components/ChatBubble.tsx
import React from "react";
import { View, Text, StyleSheet, ActivityIndicator } from "react-native";
import { Avatar, Card, Colors } from "react-native-ui-lib";
import Markdown from "react-native-markdown-display";
import CloudIA from "@/assets/images/cloudia.png";
import { FontAwesome6 } from "@expo/vector-icons";

interface Props {
	side: "left" | "right";
	name: string;
	message: string;
	hour: string;
	extraData?: Array<{ pdf: string; data: Record<string, any> }>;
	loading?: boolean;
	files?: Array<{ name: string; data: string }>;
}

const ChatBubble: React.FC<Props> = ({ side, name, message, hour, extraData, loading, files }) => {
	function getColumnsFromExtraData(pdfData: Record<string, any>) {
		if (!pdfData) return [];
		return Object.keys(pdfData).map((key) => ({
			field: key,
			header: key,
		}));
	}

	function parseTitle(title: string) {
		const convert: Record<string, string> = {
			coes: "ções",
			encias: "ências",
		};

		let replaced = title.replace(/([A-Z])/g, " $1").replace(/^./, (str) => str.toUpperCase());

		for (const key in convert) {
			if (replaced.includes(key)) replaced = replaced.replace(key, convert[key]);
		}

		return replaced;
	}

	return (
		<View style={styles.container}>
			<View style={[styles.chat, side === "left" ? styles.chatStart : styles.chatEnd]}>
				{side === "left" ? (
					<Avatar source={CloudIA} size={50} containerStyle={styles.avatar} />
				) : (
					<View style={styles.avatar}>
						<FontAwesome6 name="user-circle" size={50} color={Colors.grey40} />
					</View>
				)}
				<View style={styles.messageContainer}>
					{!loading ? (
						<>
							<Text style={styles.header}>
								{name} <Text style={styles.time}>{hour}</Text>
							</Text>
							<Markdown>{message}</Markdown>
						</>
					) : (
						<ActivityIndicator size="small" color={Colors.grey30} />
					)}

					{files && (
						<View style={styles.filesContainer}>
							{files.map((file, index) => (
								<View key={index} style={styles.fileItem}>
									<Text style={styles.fileName}>📄 {file.name}</Text>
								</View>
							))}
						</View>
					)}

					{extraData &&
						extraData.map((pdf, index) => (
							<View key={index} style={styles.extraDataContainer}>
								<Text style={styles.extraHeader}>Detalhes do arquivo: {pdf.pdf}</Text>
								{getColumnsFromExtraData(pdf.data).map((column, colIndex) => (
									<Card key={colIndex} style={styles.card}>
										<Text style={styles.cardTitle}>{parseTitle(column.header)}</Text>
										<Text style={styles.cardContent}>{pdf.data[column.field] || "Sem dados"}</Text>
									</Card>
								))}
							</View>
						))}
				</View>
			</View>
		</View>
	);
};

const styles = StyleSheet.create({
	container: {
		flex: 1,
		padding: 10,
	},
	chat: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginVertical: 5,
	},
	chatStart: {
		justifyContent: "flex-start",
	},
	chatEnd: {
		justifyContent: "flex-end",
	},
	avatar: {
		marginRight: 10,
	},
	messageContainer: {
		maxWidth: "80%",
		padding: 8,
		borderRadius: 10,
		backgroundColor: Colors.grey60,
	},
	header: {
		fontWeight: "bold",
		fontSize: 14,
		color: Colors.grey10,
	},
	time: {
		fontSize: 10,
		color: Colors.grey40,
	},
	message: {
		fontSize: 16,
		color: Colors.grey20,
	},
	filesContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		marginTop: 5,
	},
	fileItem: {
		backgroundColor: Colors.grey50,
		padding: 5,
		borderRadius: 5,
		marginRight: 5,
		marginTop: 5,
	},
	fileName: {
		fontSize: 14,
		color: Colors.grey20,
	},
	extraDataContainer: {
		marginTop: 10,
	},
	extraHeader: {
		fontSize: 14,
		fontWeight: "bold",
	},
	card: {
		backgroundColor: Colors.grey70,
		padding: 8,
		marginVertical: 5,
		borderRadius: 5,
	},
	cardTitle: {
		fontWeight: "bold",
	},
	cardContent: {
		fontSize: 14,
	},
});

export default ChatBubble;
